"""
tools/reset_pipeline_data.py
────────────────────────────
Wipe all pipeline-generated data from prod.duckdb while preserving:
  • ticker_master
  • ticker_universe_snapshot
  • sector_etf_map
  • sector_alias_map
  • daily_prices          (raw price history — expensive to re-fetch)
  • daily_features        (engineered features — expensive to re-compute)
  • earnings_calendar     (external reference data)
  • macro_events_calendar (external reference data)

Everything generated by the pipeline run is deleted:
  strategy_configs, runtime_configs, config_activation_log,
  pipeline_runs, pipeline_locks,
  step3_candidates, step4_analysis, step5_proposals,
  outcome_tracking_queue, signal_outcomes,
  data_repair_queue, feature_rebuild_log,
  ai_reviews, execution_decisions,
  schema_versions (cleared so schema re-applies cleanly on next init)

Usage:
    python tools/reset_pipeline_data.py
    python tools/reset_pipeline_data.py --db-path path/to/prod.duckdb
    python tools/reset_pipeline_data.py --dry-run
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Tables to DELETE (pipeline-generated data — safe to wipe).
# Order matters: child rows before parent rows where FK-like logic applies.
# ---------------------------------------------------------------------------
_WIPE_TABLES: list[str] = [
    "ai_reviews",
    "execution_decisions",
    "signal_outcomes",
    "outcome_tracking_queue",
    "step5_proposals",
    "step4_analysis",
    "step3_candidates",
    "feature_rebuild_log",
    "data_repair_queue",
    "config_activation_log",
    "runtime_configs",
    "strategy_configs",
    "pipeline_locks",
    "pipeline_runs",
    "schema_versions",
]

# Tables that are explicitly preserved (listed here for documentation only).
_KEEP_TABLES: list[str] = [
    "ticker_master",
    "ticker_universe_snapshot",
    "sector_etf_map",
    "sector_alias_map",
    "daily_prices",
    "daily_features",
    "earnings_calendar",
    "macro_events_calendar",
]


def _default_db_path() -> Path:
    """Resolve prod.duckdb relative to this script's location."""
    here = Path(__file__).resolve().parent
    candidates = [
        here.parent / "data" / "prod.duckdb",
        here.parent / "prod.duckdb",
        here / "prod.duckdb",
    ]
    for p in candidates:
        if p.exists():
            return p
    return candidates[0]  # return first candidate even if missing (error below)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Reset pipeline data while keeping ticker/price/feature data."
    )
    parser.add_argument(
        "--db-path",
        type=Path,
        default=None,
        help="Path to prod.duckdb (auto-detected if omitted)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be deleted without executing",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Skip confirmation prompt",
    )
    args = parser.parse_args(argv)

    db_path: Path = args.db_path or _default_db_path()

    if not db_path.exists():
        print(f"ERROR: DB not found at {db_path}", file=sys.stderr)
        print("Use --db-path to specify the correct path.", file=sys.stderr)
        return 1

    print(f"Target DB : {db_path}")
    print()
    print("Tables to WIPE (pipeline-generated data):")
    for t in _WIPE_TABLES:
        print(f"  DELETE FROM {t}")
    print()
    print("Tables to KEEP (reference / price / feature data):")
    for t in _KEEP_TABLES:
        print(f"  {t}")
    print()

    if args.dry_run:
        print("DRY RUN — no changes made.")
        return 0

    if not args.yes:
        answer = input("Proceed? [yes/N] ").strip().lower()
        if answer != "yes":
            print("Aborted.")
            return 0

    try:
        import duckdb
    except ImportError:
        print("ERROR: duckdb not installed. Run: pip install duckdb", file=sys.stderr)
        return 1

    conn = duckdb.connect(str(db_path))
    try:
        conn.execute("BEGIN TRANSACTION")
        counts: dict[str, int] = {}
        for table in _WIPE_TABLES:
            # Check if table exists before deleting.
            exists = conn.execute(
                "SELECT COUNT(*) FROM information_schema.tables "
                "WHERE table_name = ?",
                [table],
            ).fetchone()[0]
            if not exists:
                print(f"  SKIP (not found): {table}")
                continue
            n = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            conn.execute(f"DELETE FROM {table}")
            counts[table] = n
            print(f"  Deleted {n:>6,} rows from {table}")
        conn.execute("COMMIT")
    except Exception as exc:
        conn.execute("ROLLBACK")
        print(f"\nERROR: {exc}", file=sys.stderr)
        print("ROLLBACK applied — no changes committed.", file=sys.stderr)
        conn.close()
        return 1
    finally:
        conn.close()

    total = sum(counts.values())
    print()
    print(f"Done. {total:,} total rows deleted across {len(counts)} tables.")
    print("Re-initialize the pipeline to apply fresh strategy configs.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
